language: python
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.5
    env: TOXENV=py35
  - python: 3.5
    env: TOXENV=quality
  - python: 3.6
    env: TOXENV=py36
cache:
- pip
script:
- pytest
deploy:
  provider: pypi
  user: htlemke
  distributions: sdist bdist_wheel
  true:
    tags: true
  password:
    secure: gKJ6o06j97OSvtdQcOfArqDavSK4tcyLOYLHJq6+4AwchfKnZBif+eZkIuyeTsZdwE30hg+akuTZ6r4MD1XlVeIfZhE4J5bd+rl90G6iQUqRypJK4pI9JSjWV6Vf44FxqpymExqlzeXkDnBR+ZH6LYVCrioZr/hfjnwnXgOdvnA6q+RvLTvJJ43xMCMdm/nLBtbke8CjCiWIt626cepUdqmKJQZha0uslCq/+vl9Z3RrWZZMRMmZ4KdIsN7U4oN0MNhbcZ39qM3ybM74ujgfr6qRNjP04AQ3SlVEiNrl1ouBxkDPPVz5vCmpOKIjsxqctwrXDGqtvvl92KgrDRBFTBawxhETYZd5/M24mCdrMM7qVzKgm3vTMAQrJ08aBMJaou8nZ5pet9exMTJZ1MlPtCeBf1Ap6S1htMdNUJO4+ERLGTPl4giU0n/N+KQOQZV1dhOenUIJHMBg2FyYvzyOiNl4yKKWrvLt7LQhvWYvSPo85f5vxaYcKbB3kqyzehbtAuOM20uJYvB6EgBp17rnnWPIa1z/n698Yw4y83NPXY5AHHwVbPJEODwfCdyPl7cMUeE8vHKyjwArqV3XU8lQiACZddlxTgS1WcMtj7/mM1mZqk0RtNiH86rpqPpnZcqX7jzgV/l00iG+fuKqUZGfKFmbhRSnAl6MBi4P8nECgog=
